resources:
    repositories:
        -   repository: templates
            type: git
            name: DevOps/BuildTemplates

queue:
    name: Hosted Ubuntu 1604

name: 2.0.$(NextBuildNumber)$(rev:.r)

trigger:
    branches:
        include:
            - master

variables:
    BuildConfiguration: 'Release'

steps:
    -   template: SetBuildDate.yml@templates
    -   template: EmptyDirectory.yml@templates

    -   template: Clone-BuildTemplates.yml@templates
    -   template: Clone-Logixware.Web.Blazor.Fluxor.yml@templates
    -   template: Clone-Blazor.Fluxor.yml@templates
        parameters:
            Branch: 'master'

    -   template: SetAssemblyVersion.yml@templates
        parameters:
            ProjectName: 'Logixware.Web.Blazor.Fluxor'

    -   template: BuildAndUploadLibrary.yml@templates
        parameters:
            ProjectName: 'Logixware.Web.Blazor.Fluxor'

    -   template: IncrementBuildNumber.yml@templates
